// <auto-generated />
namespace EgyGobs.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Updates_jobs_model1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Updates_jobs_model1));
        
        string IMigrationMetadata.Id
        {
            get { return "202009291712129_Updates_jobs_model1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
