// <auto-generated />
namespace EgyGobs.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddJobRelationWithUsers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddJobRelationWithUsers));
        
        string IMigrationMetadata.Id
        {
            get { return "202010030053062_AddJobRelationWithUsers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
